[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cards",
    "pytest>=9.0.1",
]

[tool.uv.workspace]
members = [
    "cards_proj",
]

[tool.uv.sources]
cards = { workspace = true }
